apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: alpine:3.13
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: LOG_LEVEL
        value: info
    command: ["sh","-c","sleep 100000"]
    envFrom:
      - configMapRef:
          name: appconfig
          
