apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: recreate-nginx
  template:
    metadata:
      labels:
        app: recreate-nginx
    spec:
      containers:
      - name: recreate-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
