apiVersion: apps/v1
kind: Deployment
metadata:
  name: recreate-nginx
spec:
  strategy: 
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: recreate-nginx
  template:
    metadata:
      labels:
        app: recreate-nginx
    spec:
      containers:
      - name: recreate-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "20Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
