apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  serviceAccountName: testsa
  containers:
  - name: mycontainer
    image: alpine:3.13
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "40Mi"
        cpu: "10m"
    command:
      - "sh"
      - "-c"
      - "sleep 1000"
