apiVersion: v1
kind: Pod
metadata:
  name: two-container
spec:
  containers:
  - name: web
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    ports:
      - containerPort: 80
        hostPort: 80
  - name: curl
    imagePullPolicy: IfNotPresent
    image: nginx
    resources:
      limits:
        memory: "32Mi"
        cpu: "50m"
    command: ["/bin/sh","-c","while : ; do curl http://localhost/; sleep 30; done"]
