apiVersion: v1
kind: Pod
metadata:
  name: secretfromfile
  labels:
    name: secretFromFile
spec:
  containers:
  - name: secretfromfile
    # command:
    #   - "/bin/sh"
    args:
      - /bin/sh
      - -c
      - echo UserName;cat /mnt/db-creds/user;echo Password;cat /mnt/db-creds/pass;sleep 6000
      # - 
    image: alpine:3.13
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    volumeMounts:
      - mountPath: /mnt/db-creds
        name: creds
        readOnly: true
  volumes:
    - name: creds
      secret:
        secretName: creds

